import React from 'react';
import Link from 'next/link';

export const metadata = {
  title: 'Terms of Service | Smart Solar Energy',
  description: 'Terms of Service for Smart Solar Energy And Electricals (PVT) LTD',
};

export default function TermsOfService() {
  return (
    <main className="min-h-screen pt-32 pb-16 px-6 relative bg-[#0B192C] text-white overflow-hidden">
      {/* Decorative Background Glows */}
      <div className="absolute top-0 left-1/4 w-[500px] h-[500px] bg-[#73b042] opacity-10 blur-[120px] rounded-full pointer-events-none"></div>
      <div className="absolute bottom-0 right-1/4 w-[400px] h-[400px] bg-[#73b042] opacity-10 blur-[120px] rounded-full pointer-events-none"></div>

      <div className="max-w-4xl mx-auto relative z-10">
        <Link 
          href="/" 
          className="inline-flex items-center text-[#73b042] hover:text-white transition-colors mb-8 group font-medium"
        >
          <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="mr-2 group-hover:-translate-x-1 transition-transform">
            <line x1="19" y1="12" x2="5" y2="12"></line>
            <polyline points="12 19 5 12 12 5"></polyline>
          </svg>
          Back to Home
        </Link>
        
        <div className="bg-white/[0.02] border border-white/10 rounded-2xl p-6 md:p-12 backdrop-blur-md shadow-2xl">
          <h1 className="text-4xl md:text-5xl font-bold mb-8 text-white">Terms of Service</h1>
          
          <div className="prose prose-lg max-w-none text-gray-300">
        <p className="mb-6">
          Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
        </p>

        <h2 className="text-2xl font-bold mt-8 mb-4 text-white">1. Acceptance of Terms</h2>
        <p className="mb-6">
          By accessing and using this website, you accept and agree to be bound by the terms and provision of this agreement. In addition, when using these particular services, you shall be subject to any posted guidelines or rules applicable to such services.
        </p>

        <h2 className="text-2xl font-bold mt-8 mb-4 text-white">2. Description of Service & Accuracy of Information</h2>
        <p className="mb-6">
          Smart Solar Energy And Electricals (PVT) LTD provides users with access to a rich collection of resources, including various communications tools, contact forms to request free consultations for residential or commercial solar, and our interactive Solar Calculator.
        </p>
        <p className="mb-6">
          Please note that the results, savings estimates, system capacity (kW), and panel counts generated by the Solar Calculator are for informational and estimation purposes only. They do not constitute a binding quote or guarantee of actual system performance or financial savings. A custom consultation is required for an exact system determination.
        </p>

        <h2 className="text-2xl font-bold mt-8 mb-4 text-white">3. Privacy Policy</h2>
        <p className="mb-6">
          Registration Data and certain other information about you is subject to our Privacy Policy. For more information, see our full privacy policy here or on the respective link on the website footer.
        </p>

        <h2 className="text-2xl font-bold mt-8 mb-4 text-white">4. User Conduct</h2>
        <p className="mb-6">
          You agree to not use the Service to:
        </p>
        <ul className="list-disc pl-6 mb-6">
          <li>Upload, post, email or otherwise transmit any Content that is unlawful, harmful, threatening, abusive, harassing, defamatory, vulgar, or obscene.</li>
          <li>Harm minors in any way.</li>
          <li>Impersonate any person or entity.</li>
          <li>Forge headers or otherwise manipulate identifiers in order to disguise the origin of any Content transmitted.</li>
        </ul>

        <h2 className="text-2xl font-bold mt-8 mb-4 text-white">5. Modifications to Service</h2>
        <p className="mb-6">
          Smart Solar Energy reserves the right at any time and from time to time to modify or discontinue, temporarily or permanently, the Service (or any part thereof) with or without notice. You agree that Smart Solar Energy shall not be liable to you or to any third party for any modification, suspension or discontinuance of the Service.
        </p>

        <h2 className="text-2xl font-bold mt-8 mb-4 text-white">6. Contact Information</h2>
        <p className="mb-6">
          If you have any questions or comments about these Terms of Service as outlined above, you can contact us at:
          <br /><br />
          <strong>Smart Solar Energy And Electricals (PVT) LTD</strong><br />
          No: 125, Aluthwaththa,<br />
          Amunugama, Gunnapana, Kandy<br />
          Email: info@smartsolar.lk<br />
          Phone: 076 828 3962
        </p>
          </div>
        </div>
      </div>
    </main>
  );
}
